#!/usr/bin/env bash

echo "5*3 = $((5*3))"
echo "5-3 = $((5-3))"
echo "5+3 = $((5+3))"
echo "500*3% = $((500*3/100))"
echo "568945*33% = $((568945*33/100))"

echo "scale=1; 5/3" | bc

PI=3.141592
radius=1
area=$(echo "scale=2; $PI*$radius^2" | bc)

echo "circle area: $area"
