#!/usr/bin/env bash

lenght=$1
width=$2

area=$(($lenght*$width))
perimeter=$((2*($lenght+$width)))

echo "A rectangle with lenght $lenght and width $width has perimeter: $perimeter and area: $area" 
