#!/usr/bin/env bash

# range-based for loop (brace expansion)
for i in {1..6}; do
    echo "cool_$i"
done

i=1
# list-based for loop
for animal in kangaroo rabbit dog cat; do
    echo "Animal $i: $animal"
    ((i+=1))
done


# C-style for-loop instead if having variable

end=5

for ((i=0; i<end; i++)); do
    echo "$((i*2))"
done
