#!/usr/bin/env bash

# IFS - internal field separator -> separates space, tabs and newlines

while IFS= read -r filename; do
    if [[ -f "$filename" ]]; then
    echo "$filename is a file"
else
    echo "$filename not found"
fi
done < assets/filelist
